# errno.EINPROGRESS

Operation now in progress.

This error is mapped to the exception [`BlockingIOError`](/exceptions/BlockingIOError.md).

### Syntax

```python
errno.EINPROGRESS
```
